# This workflow will build a Java project with Gradle
# For more information see: https://docs.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Get commit ID
        id: vars
        run: echo "commit_id=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload JAR to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ env.commit_id }}
          name: velocity-proxy-${{ env.commit_id }}
          files: proxy/build/libs/velocity-proxy-*-all.jar
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
